# Nom de l'application
spring.application.name=bank-account-service

# Port du serveur
server.port=8085

# Configuration de la base de données PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bank_account_db}
spring.datasource.username=dbadmin
spring.datasource.password=secret123
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.show-sql=true

# Configuration de la serialisation Axon
axon.serializer.events=jackson
axon.serializer.messages=xstream
axon.serializer.general=jackson

# Configuration du serveur Axon
axon.axonserver.enabled=true
axon.axonserver.servers=localhost
